name: aqua
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  auto-creation-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Version golangci-lint
        id: golangci-lint
        run: |
          version=$(yq '.packages[]' aqua.yaml | grep 'golangci' | cut -d "@" -f 2)
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@d6238b002a20823d52840fda27e2d4891c5952dc # v4.0.1
        with:
          version: ${{ steps.golangci-lint.outputs.version }}
          args: --allow-parallel-runners
