name: auto merge renovate
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    types:
      - opened
defaults:
  run:
    shell: bash
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ startsWith( github.head_ref , 'renovate') }}
    steps:
      - name: Check branch
        run: echo "${{ github.head_ref }}"
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@0f859bf9e69e887678d5bbfbee594437cb440ffe # v2.1.0
        with:
          app-id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Auto merge
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh pr edit "${PR_URL}" --add-label "renovate"
          gh pr review --approve "${PR_URL}"
          gh pr edit "${PR_URL}" --title "(auto merged) ${PR_TITLE}"
          gh pr merge --auto --merge "${PR_URL}"
